// data.js
const data = {
    nodes: [
        { id: "Puszysta Oaza", members: 281, boosts: 29, partnerships: [] },
        { id: "New Arctic Furries", members: 35, boosts: 0, partnerships: ["Futrzaki na Fali", "Nasze Futrzaste Grono"] },
        { id: "Kolorowa Zatoczka", members: 92, boosts: 0, partnerships: ["Futrzaki na Fali", "Planeta Futrzaków", "New Foxing Town", "Futrzaste Miasto Pizzy", "Synowie ślimaka V2"] },
        { id: "Futrzasta Piwnica Przyjaźni", members: 102, boosts: 0, partnerships: [] },
        { id: "Polski Serwer Furry 2", members: 385, boosts: 0, partnerships: ["Futrzaki na Fali", "Futrzaste Miasto Pizzy", "New Foxing Town", "Planeta Futrzaków", "Viper's Pit", "Boykissers Heaven", "FutrzakOwO", "FurryBox", "FURRYWORLD", "Furaski", "Futrzasta Centrala"] },
        { id: "Futrzaste Miasto Pizzy", members: 823, boosts: 9, partnerships: ["Pyrkon Furries", "Futrzasta Oceania", "Kolorowa Zatoczka", "Futrzaki na Fali", "Planeta Futrzaków", "Polski Serwer Furry 2", "Boykissers Heaven", "Futrzasta Krypta", "New Foxing Town", "Viper's Pit", "Futrzasta Serwerownia", "Strawtilla's World", "Lisi cień", "Nasze Futrzaste Grono"] },
        { id: "FurHeaven", members: 584, boosts: 0, partnerships: ["Dolina Futer", "Yutan", "Futrzasta Centrala"] },
        { id: "Parrot Cafe", members: 527, boosts: 15, partnerships: ["New Foxing Town", "Pyrkon Furries", "BFSiP", "Boykissers Heaven"] },
        { id: "Furrasowy Hellfire", members: 399, boosts: 7, partnerships: ["Futrzaki na Fali", "Kolorowe Futra", "Night City Renascence", "Trójmiejskie Futra"] },
        { id: "Tajne Zgromadzenie Futrzaków", members: 1674, boosts: 28, partnerships: [] },
        { id: "Futrzasta Oceania", members: 230, boosts: 0, partnerships: ["Futrzaste Miasto Pizzy", "Strawtilla's World", "Smocza Przystań", "Liliowe futerka", "Boykissers Heaven", "Futrzaki na Fali", "Lisia Norka", "Furaski"] },
        { id: "New Foxing Town", members: 393, boosts: 14, partnerships: ["Planeta Futrzaków", "Pyrkon Furries", "Futrzaste Miasto Pizzy", "Viper's Pit", "Futrzaki na Fali", "Polski Serwer Furry 2", "Cs'owe Futerka", "Futrzasta Karczma", "Trójmiejskie Futra", "Parrot Cafe", "Boykissers Heaven", "Konfederacja Lisowska", "Kolorowa Zatoczka"] },
        { id: "Stacja Pandka", members: 769, boosts: 16, partnerships: ["Furasowa Republika", "Pyrkon Furries"] },
        { id: "Pyrkon Furries", members: 806, boosts: 1, partnerships: ["Gwiazdeczki Cosmiego", "Fragonia Factory", "Tayland", "Futrzaste Miasto Pizzy", "Parrot Cafe", "New Foxing Town", "Stacja Pandka", "Lisia Norka", "Futrzasty zakątek", "Night City Renascence", "FutrzakOwO", "FurryBox", "Wylęgarnia"] },
        { id: "Konfederacja Lisowska", members: 193, boosts: 3, partnerships: ["Planeta Futrzaków", "Nasze Futrzaste Grono", "New Foxing Town"] },
        { id: "Futrzasty Zakątek", members: 44, boosts: 0, partnerships: ["Futrzasta Kawiarnia"] },
        { id: "Tajemnicze Futrzaki", members: 87, boosts: 1, partnerships: [] },
        { id: "Lisia Norka", members: 319, boosts: 2, partnerships: ["FURRYWORLD", "Pyrkon Furries", "Furrasowe Arty", "Futrzaste Plemię", "Furaski", "Futrzasta Oceania", "Dolina Futer", "Futrzasty discord", "Furry obóz RP", "Futrzaki na Fali"] },
        { id: "Lazurowe Futerka", members: 38, boosts: 0, partnerships: [] },
        { id: "Tayland", members: 209, boosts: 3, partnerships: ["Pyrkon Furries", "Gwiazdeczki Cosmiego", "Fragonia Factory"] },
        { id: "Futrzasta Chatka", members: 190, boosts: 0, partnerships: ["Furrasowy kącik", "FurryBox", "FutrzakOwO", "Polskie Smoki", "Futrzasty obóz"] },
        { id: "Furry Night PL", members: 115, boosts: 0, partnerships: ["Furasowy Las", "Futrzaki na Fali", "Kolorowe Futra"] },
        { id: "Futrzasty zakątek", members: 342, boosts: 7, partnerships: ["Kemi's Furry Place", "Gwiazdeczki Cosmiego", "Pyrkon Furries"] },
        { id: "Furrysławia", members: 149, boosts: 0, partnerships: [] },
        { id: "Futerkowy Las", members: 51, boosts: 0, partnerships: ["Futrzasta Krypta"] },
        { id: "Futrzaki na Fali", members: 1711, boosts: 19, partnerships: ["Lisia Norka", "Trójmiejskie Futra", "Kolorowa Zatoczka", "Furry Night PL", "Furrasowy Hellfire", "Synowie ślimaka V2", "Futrzaste Miasto Pizzy", "Rzeczpospolita Furska", "Boykissers Heaven", "Smocza Przystań", "Viper's Pit", "New Foxing Town", "Futrzasty Serwer", "BFSiP", "New Arctic Furries", "Nasze Futrzaste Grono", "Liliowe futerka", "Futrzasta Oceania", "Krakersy", "Polski Serwer Furry 2"] },
        { id: "Planeta Futrzaków", members: 497, boosts: 3, partnerships: ["Kolorowa Zatoczka", "Futrzaste Miasto Pizzy", "Boykissers Heaven", "Polski Serwer Furry 2", "New Foxing Town", "Viper's Pit", "Synowie ślimaka V2", "Futrzasta Serwerownia", "Konfederacja Lisowska", "Nasze Futrzaste Grono"] },
        { id: "Night City Renascence", members: 90, boosts: 0, partnerships: ["Pyrkon Furries", "Furrasowy Hellfire"] },
        { id: "Boykissers Heaven", members: 834, boosts: 14, partnerships: ["Futrzaki na Fali", "Planeta Futrzaków", "Rzeczpospolita Furska", "New Foxing Town", "Futrzaste Miasto Pizzy", "Viper's Pit", "BFSiP", "Nasze Futrzaste Grono", "Polski Serwer Furry 2", "Parrot Cafe", "Smocza Przystań", "Liliowe futerka", "Art Futerka", "Futrzasta Oceania"] },
        { id: "Futerkowa Przystań", members: 218, boosts: 2, partnerships: [] },
        { id: "Kolorowe Futra", members: 147, boosts: 0, partnerships: ["Furry Night PL", "Furrasowy Hellfire", "Rzeczpospolita Furska", "Viper's Pit"] },
        { id: "Nasze Futrzaste Grono", members: 208, boosts: 5, partnerships: ["Futrzasta Krypta", "Boykissers Heaven", "Futrzaste Miasto Pizzy", "Rzeczpospolita Furska", "Wilkowice", "Planeta Futrzaków", "Futrzana Piwnica", "New Arctic Furries", "Art Futerka", "Futrzaki na Fali", "Futrzasta Serwerownia", "Konfederacja Lisowska"] },
        { id: "Futrzana Dolina", members: 38, boosts: 0, partnerships: [] },
        { id: "Futrzasty Serwer", members: 89, boosts: 0, partnerships: ["Futrzaki na Fali"] },
        { id: "Norka Futrzaków", members: 192, boosts: 2, partnerships: [] },
        { id: "Liliowe futerka", members: 78, boosts: 0, partnerships: ["Boykissers Heaven", "Futrzaki na Fali", "Futrzasta Oceania", "F U R Y"] },
        { id: "Dragon's Party", members: 52, boosts: 2, partnerships: [] },
        { id: "Smocza Przystań", members: 118, boosts: 7, partnerships: ["Futrzaki na Fali", "Boykissers Heaven", "Futrzasta Oceania"] },
        { id: "CyberFutrzaki 2621", members: 90, boosts: 11, partnerships: [] },
        { id: "Futrzasta Serwerownia", members: 142, boosts: 0, partnerships: ["Futrzaste Miasto Pizzy", "Futrzasta Krypta", "Nasze Futrzaste Grono", "Planeta Futrzaków"] },
        { id: "BFSiP", members: 1840, boosts: 26, partnerships: ["FutrzakOwO", "Lisi cień", "World of Furries", "FURRYWORLD", "Dolina Futer", "Futrzaki na Fali", "Boykissers Heaven", "Parrot Cafe", "FurryBox", "Futrzasta Centrala", "Wylęgarnia"] },
        { id: "Futrzasta Krypta", members: 42, boosts: 0, partnerships: ["Futrzasta Serwerownia", "Futrzaste Miasto Pizzy", "Futrzana Piwnica", "Futerkowy Las", "Nasze Futrzaste Grono"] },
        { id: "Paw Paradise", members: 54, boosts: 0, partnerships: [] },
        { id: "Art Futerka", members: 179, boosts: 0, partnerships: ["Nasze Futrzaste Grono", "Boykissers Heaven"] },
        { id: "Futerka NSFW", members: 374, boosts: 1, partnerships: [] },
        { id: "Schronisko Bartisa", members: 53, boosts: 0, partnerships: [] },
        { id: "Futrzasta Norka", members: 932, boosts: 0, partnerships: [] },
        { id: "Futrzasta Sauna", members: 49, boosts: 1, partnerships: [] },
        { id: "FURRY VR - WRLD", members: 262, boosts: 2, partnerships: [] },
        { id: "Krakersy", members: 122, boosts: 4, partnerships: ["Futrzaki na Fali"] },
        { id: "Dolina Futer", members: 416, boosts: 0, partnerships: ["BFSiP", "FurHeaven", "Lisi cień", "Lisia Norka", "FurryBox", "FURRYWORLD"] },
        { id: "Yutan", members: 153, boosts: 0, partnerships: ["Futrzasty obóz", "Furrasolandia", "FurHeaven", "Lisi cień"] },
        { id: "Futrzasty obóz", members: 27, boosts: 0, partnerships: ["Futrzasta Chatka", "Yutan", "Fragonia Factory"] },
        { id: "Viper's Pit", members: 181, boosts: 0, partnerships: ["Futrzaki na Fali", "Planeta Futrzaków", "New Foxing Town", "Futrzaste Miasto Pizzy", "Polski Serwer Furry 2", "Boykissers Heaven", "Kolorowe Futra"] },
        { id: "Furrasolandia", members: 66, boosts: 0, partnerships: ["Yutan"] },
        { id: "Strawtilla's World", members: 73, boosts: 0, partnerships: ["Fox Community", "Futrzasta Oceania", "Futrzaste Miasto Pizzy"] },
        { id: "FURREN TAG", members: 81, boosts: 0, partnerships: [] },
        { id: "Cs'owe Futerka", members: 108, boosts: 0, partnerships: ["Gwiezdne Futra", "New Foxing Town"] },
        { id: "Gwiezdne Futra", members: 32, boosts: 0, partnerships: ["Cs'owe Futerka"] },
        { id: "Carrie's Community", members: 38, boosts: 0, partnerships: [] },
        { id: "F U R Y", members: 25, boosts: 0, partnerships: ["Liliowe futerka"] },
        { id: "Trójmiejskie Futra", members: 125, boosts: 1, partnerships: ["Furrasowy Hellfire", "Futrzaki na Fali", "New Foxing Town"] },
        { id: "Furasowa Republika", members: 323, boosts: 7, partnerships: ["Stacja Pandka"] },
        { id: "Furzasta Karczma", members: 247, boosts: 6, partnerships: ["New Foxing Town"] },
        { id: "Gwiazdeczki Cosmiego", members: 390, boosts: 4, partnerships: ["Futrzasty zakątek", "Pyrkon Furries", "Tayland"] },
        { id: "Fragonia Factory", members: 122, boosts: 0, partnerships: ["Pyrkon Furries", "Tayland", "FURRYWORLD", "Futrzasty obóz", "Lisi cień"] },
        { id: "Futrzasta Kawiarnia", members: 46, boosts: 0, partnerships: ["Futrzasty Zakątek"] },
        { id: "FutrzakOwO", members: 128, boosts: 0, partnerships: ["FURRYWORLD", "Futrzasta Centrala", "Futerkowa wysepka", "Lisi cień", "Polskie Smoki", "Pyrkon Furries", "Futrzasta Chatka", "BFSiP", "Polski Serwer Furry 2", "Wylęgarnia"] },
        { id: "FurryBox", members: 139, boosts: 0, partnerships: ["World of Furries", "Lisi cień", "Futrzasta Centrala", "Polski Serwer Furry 2", "Futrzaste Plemię", "Furrasowy kącik", "Dolina Futer", "Polskie Smoki", "Furry Galaxy", "Pyrkon Furries", "BFSiP", "Futrzasta Chatka"] },
        { id: "FURRYWORLD", members: 109, boosts: 0, partnerships: ["Furry Galaxy", "Futrzasta Centrala", "Lisi Lasek", "FutrzakOwO", "BFSiP", "World of Furries", "Polski Serwer Furry 2", "Lisia Norka", "Furrasowe Arty", "Dolina Futer", "Fragonia Factory"] },
        { id: "Lisi cień", members: 514, boosts: 0, partnerships: ["Futrzaste Miasto Pizzy", "Yutan", "Dolina Futer", "Fragonia Factory", "FutrzakOwO", "FurryBox", "Futrzasta Centrala", "BFSiP", "Wylęgarnia"] },
        { id: "Furaski", members: 70, boosts: 0, partnerships: ["Lisia Norka", "Polski Serwer Furry 2", "Futrzasta Oceania", "Stary Londyn"] },
        { id: "Futrzasta Centrala", members: 206, boosts: 0, partnerships: ["FurHeaven", "Lisi cień", "BFSiP", "Polski Serwer Furry 2", "FutrzakOwO", "FurryBox", "FURRYWORLD", "Furtownia", "FUTERKOWO", "FuterkOwO"] },
        { id: "Polskie Smoki", members: 246, boosts: 0, partnerships: ["FurryBox", "Futrzasta Chatka", "FutrzakOwO"] },
        { id: "Furasowy Las", members: 23, boosts: 0, partnerships: ["Furry Night PL"] },
        { id: "Futrzana Piwnica", members: 38, boosts: 0, partnerships: ["Nasze Futrzaste Grono", "Futrzasta Krypta", "Fox Community"] },
        { id: "World of Furries", members: 66, boosts: 0, partnerships: ["Lisi cień", "BFSiP", "FURRYWORLD", "FurryBox", "Futerkowa wysepka"] },
        { id: "Fox Community", members: 46, boosts: 0, partnerships: ["Strawtilla's World", "Futrzana Piwnica"] },
        { id: "Futrzasta Kafejka Internetowa", members: 50, boosts: 0, partnerships: [] },
        { id: "Furry Galaxy", members: 186, boosts: 0, partnerships: ["FURRYWORLD", "FurryBox", "FUTERKOWO", "Wylęgarnia"] },
        { id: "Lisi Lasek", members: 48, boosts: 0, partnerships: ["FURRYWORLD"] },
        { id: "Synowie ślimaka V2", members: 64, boosts: 0, partnerships: ["Futrzaki na Fali", "Planeta Futrzaków", "Kolorowa Zatoczka"] },
        { id: "Puszyste Ogonki", members: 203, boosts: 0, partnerships: [] },
        { id: "Furrasowe Arty", members: 36, boosts: 0, partnerships: ["Lisia Norka", "FURRYWORLD"] },
        { id: "Futrzaste Plemię", members: 83, boosts: 0, partnerships: ["Lisia Norka", "FurryBox"] },
        { id: "Futrzasty discord", members: 44, boosts: 0, partnerships: ["Lisia Norka"] },
        { id: "Furry obóz RP", members: 88, boosts: 0, partnerships: ["Lisia Norka"] },
        { id: "Rzeczpospolita Furska", members: 241, boosts: 2, partnerships: ["Nasze Futrzaste Grono", "Boykissers Heaven", "Futrzaki na Fali"] },
        { id: "Furrasowy kącik", members: 165, boosts: 0, partnerships: ["Futrzasta Chatka", "FurryBox"] },
        { id: "Futerkowa wysepka", members: 272, boosts: 0, partnerships: ["FutrzakOwO", "World of Furries"] },
        { id: "Kemi's Furry Place", members: 40, boosts: 0, partnerships: ["Futrzasty zakątek"]},
        { id: "Wilkowice", members: 83, boosts: 2, partnerships: ["Nasze Futrzaste Grono"]},
        { id: "Stary Londyn", members: 21, boosts: 0, partnerships: ["Furaski"]},
        { id: "Furtownia", members: 340, boosts: 14, partnerships: ["FURRYWORLD", "Futrzasta Centrala"]},
        { id: "FUTERKOWO", members: 31, boosts: 0, partnerships: ["Furry Galaxy", "Futrzasta Centrala"]},
        { id: "FuterkOwO", members: 38, boosts: 0, partnerships: ["Futrzasta Centrala"]},
        { id: "Futrzasta Karczma", members: 247, boosts: 6, partnerships: ["New Foxing Town", "Electron's Hub"]},
        { id: "Electron's Hub", members: 304, boosts: 7, partnerships: ["Futrzasta Karczma", "Gwiazdeczki Cosmiego"]},
        { id: "Wylęgarnia", members: 126, boosts: 0, partnerships: ["Furry Galaxy", "FutrzakOwO", "BFSiP", "Lisi cień", "Pyrkon Furries"]}

    ],
    links: []
};
